### ISSUE TITLE
Provide Gradle quick start instructions on README

### ISSUE THREAD

**Issue by eriwen** [ErnestOrt/Trampoline#15]
As a Gradle user, I'd like quick start instructions for Trampoline. This is done for Maven only. 

![screen shot 2017-09-01 at 8 18 12 am](https://user-images.githubusercontent.com/51534/29976250-3c229000-8eee-11e7-8ec9-53a1be7efe38.png)

Would love to see Gradle there, too :)

**Comment by ErnestOrt** [comment]
Sure, completely agree. I will review it and solve it as soon as possible. Thanks for your feedback!

**Comment by ErnestOrt** [comment]
solved on v3.4.

Moreover, now you can start Trampoline using ./gradlew (or gradlew.bat) bootRun.

Cheers!

**Comment by eriwen** [comment]
Thank you very much!
