### ISSUE TITLE
Git Integration

### ISSUE THREAD

**Issue by 72MiguelGomes** [ErnestOrt/Trampoline#20]
Would be great have an integration with git, to allow pull the new code and restart the service for services where we are not working on that moment but we need the latest version.

**Comment by ErnestOrt** [comment]
Thanks for your feedback @72MiguelGomes! It would be a great feature definitely, as soon as possible, it will be implemented. Cheers!

**Comment by linux-china** [comment]
it's a nice feature :)   please add create service from git url.

**Comment by ErnestOrt** [comment]
@72MiguelGomes implemented on 3.7. 

@linux-china another ticket created for your enhancement.

Cheers!

**Comment by 72MiguelGomes** [comment]
Thanks @ErnestOrt
