### ISSUE TITLE
register by using maven artifact ,group and version

### ISSUE THREAD

**Issue by cforce** [ErnestOrt/Trampoline#21]
1.) Provide application register option using maven artifact ,group and version.
2.) The version dialog may propose optional dropdown with available version (mots recent on top)
3.) The artifact is downloaded via maven from repository.
4.) Save configuration history for registered application's arifact
5.)Configure destination path for downloaded artifacts

**Comment by ErnestOrt** [comment]
Hi @cforce, this doesn't accomodate on the project right now. Thanks for your ideas.

**Comment by cforce** [comment]
Not sure why you think such way. For many teams sharing my Microservice landscape one team might need another teams Microservice to be started for their integration test but don't need to pull it from source but use the jar artifact.
To start a spring boot app from jar you can use the same mechanism as you do now from sec, so it's just another context.

**Comment by ErnestOrt** [comment]
Sure, I am not saying it is a bad idea. The thing is that we need to optimize our resources and there are more priority tasks right now. I have it on backlog but will not be implemented on the near future. Thanks & Cheers!
