### ISSUE TITLE
Shutdown icon should use Font-Awesome "power-off"

### ISSUE THREAD

**Issue by JTWalraven** [ErnestOrt/Trampoline#35]
Hey there,
Thanks for your awesome project! Wouldn't it seem to make more sense/be more intuitive if the shutdown button used the "power-off" icon from FontAwesome?
```html
<i class="fa fa-power-off"></i>
```

**Comment by JTWalraven** [comment]
Made a PR #40 in case you agree.

**Comment by ErnestOrt** [comment]
Looks cooler! Thanks @JTWalraven
