### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by JTWalraven** [ErnestOrt/Trampoline#39]
I noticed that there are a lot of `printStackTrace` statements for errors and a lack of informative statements on expected behavior. It would be beneficial if a logging library were incorporated and used within Trampoline. This would improve log readability.

SLF4J with Logback?

**Comment by JTWalraven** [comment]
@ErnestOrt Once again, I can help on this. Just let me know.

**Comment by ErnestOrt** [comment]
Definitely @JTWalraven go for it. 

As an active developer, it is not something really import (server side logic is quite straight forward as you already saw) but as user would be nice to see a better actions tracker plus more meaningful traces.

SLF4J is a good choice. 

I used as follow:
private final Logger log = LoggerFactory.getLogger(****.class);

Do you prefer to keep working with PR or do you want to join as collaborator?

**Comment by ErnestOrt** [comment]
@hukacode Do you feel you can do it? If so, jump into it and send a PR when done.

**Comment by JTWalraven** [comment]
@ErnestOrt It would be great if you could add me as a collaborator.
