### ISSUE TITLE
Feature: Allow actuator endpoints on different port

### ISSUE THREAD

**Issue by RobWin** [ErnestOrt/Trampoline#52]
Hello,

awesome project. Thanks.
It would be nice if I could configure a different port for the actuator endpoints.

**Comment by ErnestOrt** [comment]
Hi @RobWin ,

Thanks for your feedback! Do not forget to star the project if you like it!

Since it sounds usefull and more users could be interested in it, we will prioritize your requirement and implemented it as soon as an slot of time will be available.

Cheers

**Comment by ErnestOrt** [comment]
@RobWin 

Wondering if this usecase scenario can be solved using VM arguments field

**Comment by RobWin** [comment]
Yes, I could even start the App with a different test profile which does not use a different port for the actuator endpoints.

**Comment by ErnestOrt** [comment]
Great! I'm going to close this ticket then.

Thanks for your feedback and have a nice week!
