### ISSUE TITLE
Dashboard for microservice

### ISSUE THREAD

**Issue by andresoviedo** [ErnestOrt/Trampoline#70]
Hi.  It would be nice to have a dashboard per microservice, in order to monitor it's performance

**Comment by cforce** [comment]
That exists already https://github.com/codecentric/spring-boot-admin


Andres Oviedo <notifications@github.com> schrieb am Sa., 11. Aug. 2018,
18:22:

**Comment by andresoviedo** [comment]
That's great.  Thanks
